### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by gusarg81** [powerdot/Minecraft-Server-Admin#6]
Hi, installed in Ubuntu 18.04 and I got this error (using install.sh script, and on ):

> sudo pm2 startup upstart
> let val = process.env[key];
>         ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Any ideas? Thanks.

**Comment by powerdot** [comment]
Hmm strange error. I guess it depends on last PM2 update. But I tried install service on my own new Digital Ocean Droplet ($10/m) and don't catch this type error.

Please, can you give me your server specs?

**Comment by gusarg81** [comment]
As I've mentioned is Ubuntu 18.04 (18.04.5 LTS). Is my own server located in a Datacenter. Is a production server.
If your install script is ok, then dependencies should not be a problem if that the case.

**Comment by gusarg81** [comment]
Weird, installed all by hand and now seems to work.

**Comment by powerdot** [comment]
Haha, don't forget to restart the machine: sometimes not enough ram after this complex installation! I'll be waiting for similar errors from more players to found problem.
Thank you!

**Comment by gusarg81** [comment]
My server has 32GB of ram, so I think that was not the problem. Also in this case, I've installed nodejs 14.x. instead of 12.x.
